# Generated by Django 5.1.6 on 2025-05-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='image file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('restaurant', models.ManyToManyField(blank=True, related_name='categories', to='branches.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='item name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('preparation_time', models.IntegerField(default=0, verbose_name='preparation time (minutes)')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='rate')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='stock quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ManyToManyField(blank=True, related_name='menu_items', to='menus.category', verbose_name='category')),
                ('restaurant', models.ManyToManyField(blank=True, related_name='menu_items', to='branches.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='MenuItemsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='image file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menus.menuitems', verbose_name='menu item')),
            ],
            options={
                'verbose_name': 'Menu Item Image',
                'verbose_name_plural': 'Menu Item Images',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='review')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menus.menuitems', verbose_name='menu item')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.profile', verbose_name='user profile')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
