# Generated by Django 5.1.6 on 2025-05-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItemsImages',
            new_name='MenuItemImages',
        ),
    ]
