# Generated by Django 5.1.6 on 2025-05-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('menus', '0002_rename_menuitemsimages_menuitemimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='branches.restaurant', verbose_name='restaurant'),
        ),
    ]
