# Generated by Django 5.1.6 on 2025-05-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('menus', '0003_reviews_is_published_reviews_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='branches.restaurant', verbose_name='restaurant'),
        ),
    ]
