# Generated by Django 5.1.6 on 2025-07-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('menus', '0004_alter_reviews_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_menu_items', to='menus.menuitems', verbose_name='menu item')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_menu_items', to='accounts.profile', verbose_name='user profile')),
            ],
            options={
                'verbose_name': 'User Favorite Menu Item',
                'verbose_name_plural': 'User Favorite Menu Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile'], name='menus_userf_user_pr_bc9a91_idx'), models.Index(fields=['menu_item'], name='menus_userf_menu_it_4cc23a_idx'), models.Index(fields=['user_profile', 'menu_item'], name='menus_userf_user_pr_81c644_idx')],
                'unique_together': {('user_profile', 'menu_item')},
            },
        ),
    ]
