# Generated by Django 5.1.6 on 2025-04-25 17:37

import django.core.validators
import django.db.models.deletion
import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branches/logo', verbose_name='logo')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(max_length=10, unique=True, validators=[utils.validations.custom_postal_code_validator], verbose_name='postal code')),
                ('phone_number1', models.CharField(max_length=11, unique=True, validators=[utils.validations.validate_phone], verbose_name='phone number1')),
                ('phone_number2', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[utils.validations.validate_phone], verbose_name='phone number2')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('website', models.URLField(verbose_name='website')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='rate')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('support_of_range_delivery', models.BooleanField(default=True, verbose_name='supports delivery in range')),
                ('out_of_range_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='out of range delivery fee')),
                ('max_out_of_range_distance', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='max out of range distance (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of the Week')),
                ('open_time', models.TimeField(verbose_name='Opening Time')),
                ('close_time', models.TimeField(verbose_name='Closing Time')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed on this day')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='branches.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Opening Hour',
                'verbose_name_plural': 'Restaurant Opening Hours',
                'ordering': ['restaurant', 'day'],
            },
        ),
    ]
