# Generated by Django 5.1.6 on 2025-07-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='phone number2 (mobile or landline)'),
        ),
    ]
