# Generated by Django 5.1.6 on 2025-07-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_restaurant_phone_number2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantopeninghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='restaurantopeninghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening Time'),
        ),
    ]
