# Generated by Django 5.1.6 on 2025-07-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_restaurantopeninghours_close_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantopeninghours',
            unique_together={('restaurant', 'day')},
        ),
    ]
